Flow mode reminders setting
swdotcom/swdc-vscode pull request #226
Opened 2021-01-27 22:26 UTC by bjacobson26

2021-01-27 22:45 UTC, o4sw commented on src/managers/FlowManager.ts
> +export let enablingFlow = false;
How does this work? exporting a variable that is later assigned a different value. But when it's imported it is a const. It might work, but also a bit confusing. Maybe just exporting getter/setter functions?

2021-01-27 23:20 UTC, bjacobson26 commented on src/managers/FlowManager.ts
> +export let enablingFlow = false;
it seems to work well. It is imported by the other file as a let, so it stays up to date. imo creating getter/setting functions makes it more complicated

2021-01-28 00:02 UTC, xavluiz requested changes

2021-01-28 00:02 UTC, xavluiz commented on src/message_handlers/flow_score.ts
> +  if (configSettings.flowModeReminders && !enablingFlow && !enabledFlow) {
there's a method we should use, not this

2021-01-28 00:04 UTC, xavluiz commented on src/managers/FlowManager.ts
> +export let enablingFlow = false;
we shouldn't use this flag. we should use "isInFlowMode()" You can put the slack related stuff inside that method so you don't have to pass it in every time but this method finds out if you've actually exited out of flow mode because of screen state changes

2021-01-28 00:08 UTC, xavluiz commented on src/managers/FlowManager.ts
> +export let enablingFlow = false;
just talked to you and this should be set correctly if we've gone out of flow, so it should be ok to use it. thanks for testing the use case

2021-01-28 00:09 UTC, xavluiz approved these changes

2021-01-28 00:15 UTC, bjacobson26 commented
here's a video: https://www.loom.com/share/0ec297c33ce6400db01b99f1d7ed0bd4

2021-01-28 04:19 UTC, merged